[pytest]
# scan everything under 'app'
testpaths = 
    app

# ensure imports like `import app...` work
pythonpath = .

# only pick up files named test_*.py
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# short tracebacks by default
addopts = --tb=short
